version: "3.8"
services:
  instakilo-user-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres,
      POSTGRES_PASSWORD: thisIsMyBankPassword4Real,
      POSTGRES_DB: instakiloUserDB
    networks:
      - instakiloNetwork
  instakilo-post-db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: safestPasswordInTheWorld
    networks:
      - instakiloNetwork
networks:
  instakiloNetwork:
  
