version: "3.8"
services:
  instakilo-user-db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_URI}
    networks:
      - instakiloNetwork
  instakilo-post-db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - instakiloNetwork
  instakilo-comments-db:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    networks:
      - instakiloNetwork
  instakilo-likes-db:
    image: rethinkdb:latest
    ports:
      - '8080:8080'  # RethinkDB web UI
      - '28015:28015' # RethinkDB client driver port
      - '29015:29015' # RethinkDB intracluster communication port
    networks:
      - instakiloNetwork
    environment:
      RETHINKDB_PASSWORD: ${RETHINKDB_PASSWORD}
networks:
  instakiloNetwork: